### ISSUE TITLE
启动客户端时报java.lang.NullPointerException

### ISSUE THREAD

**Issue by 03128crz** [liyue2008/simple-rpc-framework#1]
```
D:\spring_projects\simple-rpc-framework-master>java -jar client\target\client-1.0-SNAPSHOT-jar-with-dependencies.jar
[main] INFO com.github.liyue2008.rpc.serialize.SerializeSupport - Found serializer, class: com.github.liyue2008.rpc.nameservice.Metadata, type: 100.
[main] INFO com.github.liyue2008.rpc.serialize.SerializeSupport - Found serializer, class: java.lang.String, type: 0.
[main] INFO com.github.liyue2008.rpc.serialize.SerializeSupport - Found serializer, class: com.github.liyue2008.rpc.client.stubs.RpcRequest, type: 101.
[main] INFO com.github.liyue2008.rpc.nameservice.LocalFileNameService - Metadata:
        Classname: com.github.liyue2008.rpc.hello.HelloService
        URIs:
                rpc://localhost:9999

[main] INFO com.github.liyue2008.rpc.client.Client - 找到服务com.github.liyue2008.rpc.hello.HelloService，提供者: rpc://localhost:9999.
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
        at com.github.liyue2008.rpc.client.DynamicStubFactory.createStub(DynamicStubFactory.java:69)
        at com.github.liyue2008.rpc.NettyRpcAccessPoint.getRemoteService(NettyRpcAccessPoint.java:50)
        at com.github.liyue2008.rpc.client.Client.main(Client.java:44)
Caused by: java.lang.NullPointerException
        at com.itranswarp.compiler.JavaStringCompiler.<init>(JavaStringCompiler.java:25)
        at com.github.liyue2008.rpc.client.DynamicStubFactory.createStub(DynamicStubFactory.java:58)
        ... 2 more

**Comment by liyue2008** [comment]
报这个错误的原因是没有找到JDK的编译器：com.sun.tools.javac.api.JavacTool
你需要检查一下你本机的JDK环境。只有JRE是不行的。
